global using BuildingBlocks.Mediator.Interfaces;
global using Catalog.Api.Models;
global using Marten;
global using BuildingBlocks.Mediator.Extensions;
global using BuildingBlocks.Mediator.Behaviors;
global using Catalog.Api.Products.CreateProduct;
global using Catalog.Api.Products.GetProducts;
global using BuildingBlocks.Exceptions.Handler;
global using BuildingBlocks.Exceptions;