services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data
  
  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data
  
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
  
  messagebroker:
    container_name: messagebroker
    hostname: ecommerce-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  
  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;;Include Error Detail=true;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
  
  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;;Include Error Detail=true;
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountGrpcUrl=https://discountgrpc:8081
      - MessageBroker__Host=amqp://ecommerce-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
      - messagebroker
    ports:
      - "6001:8080"
      - "6061:8081"
    # Modified volume mounts for macOS compatibility
    volumes:
      #   - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      #   - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro
  
  discount.grpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6002:8080"
      - "6062:8081"
    # Modified volume mounts for macOS compatibility
    volumes:
      #   - ${HOME}/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      #   - ${HOME}/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      - ${HOME}/.aspnet/https:/root/.aspnet/https:ro