services:
  keycloakdb:
    image: postgres:latest

  catalogdb:
    image: postgres:latest
  
  minio:
    image: minio/minio:latest
  
  basketdb:
    image: postgres:latest

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
  
  distributedcache:
    image: redis:latest
  
  orderdb:
    image: mcr.microsoft.com/mssql/server:latest
  
  messagebroker:
    image: rabbitmq:management
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    depends_on:
      - catalogdb
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    depends_on:
      - basketdb
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
  
  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.Api/Dockerfile
  
  gatewayapi:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateways/GatewayApi/Dockerfile

  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: UserInterfaces/WebApplication/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_keycloak:
  minio_data:
  #  sql_order:
  
